# Javascript Node CircleCI 2.0 configuration file
version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v2-deps-{{ .Branch }}-
            - v2-deps-
      - run: npm ci
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run todos-e2e
      # - store_test_results:
      #     path: junit-results
      # - run:
      #     name: Running E2E tests with multiple reporters
      #     command: npm run test-multiple
      # - store_test_results:
      #     path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots


# #
# # Check https://circleci.com/docs/2.0/language-javascript/ for more details
# #
# version: 2

# defaults: &defaults
#   working_directory: ~/goodfaith
#   docker:
#     - image: circleci/node:11.13.0-stretch-browsers

# jobs:
#   build:
#     <<: *defaults
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - yarn-dependencies-11.13.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
#             - yarn-dependencies-11.13.0-{{ .Branch }}-
#             # fallback to using the latest cache if no exact match is found
#             - yarn-dependencies-11.13.0-
#       - run: yarn install --frozen-lockfile --non-interactive
#       - save_cache:
#           key: yarn-dependencies-11.13.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
#           paths:
#             - ~/.cache
#       - run: yarn start format.and.lint.check
#       - run: yarn start prepare.e2e
#       - run: yarn start test.affected.origin-master
#       - run:
#           command: yarn start e2e.ci1
#           no_output_timeout: 5m
#           environment:
#             CYPRESS_RECORD_KEY: b8ec9ad7-505f-48bb-9990-e8d5627bac26

#   cypress-2:
#     <<: *defaults
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - yarn-dependencies-11.13.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
#             - yarn-dependencies-11.13.0-{{ .Branch }}-
#             # fallback to using the latest cache if no exact match is found
#             - yarn-dependencies-11.13.0-
#       - run: yarn install --frozen-lockfile --non-interactive
#       - run: yarn start prepare.e2e
#       - run:
#           command: yarn start e2e.ci2
#           no_output_timeout: 5m
#           environment:
#             CYPRESS_RECORD_KEY: b8ec9ad7-505f-48bb-9990-e8d5627bac26

# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - cypress-2
